### ISSUE TITLE
Error on pushd package

### ISSUE THREAD

**Issue by CGarces** [xmapst/GLMV1000W-OpenWrt#1]
Hi!

After clean clone of the repository

$ chmod +x offical-openwrt.sh 
$ ./offical-openwrt.sh 

The package folder not exist so line 12 fails.

https://github.com/xmapst/GLMV1000W-OpenWrt/blob/f872e644ed14f72aa9d34ee038f6d6192678cf61/offical-openwrt.sh#L12

affer `mkdir package`, the next error is at line 115, the folder not exist.

`./offical-openwrt.sh: línea 115: pushd: feeds/packages/utils/docker-ce
`

Also consider use --single-branch --depth=1 to clone po2lmo and rtl8192eu packages.

**Comment by CGarces** [comment]
Ok, I see that openWRT is missing

git clone https://git.openwrt.org/openwrt/openwrt.git
wget https://github.com/xmapst/GLMV1000W-OpenWrt/archive/main.zip

And glue all together.

but error at 115 remains

`./offical-openwrt.sh: línea 115: pushd: feeds/packages/utils/docker-ce: No existe el fichero o el directorio
`

**Comment by CGarces** [comment]
Ok, after a proper environment setup as noted on 

https://github.com/Mange/rtl8192eu-linux-driver/issues/206#issuecomment-742884014

scripts/ipv6-helper.sh is missing I don't know if is mandatory.

**Comment by xmapst** [comment]
> Ok, after a proper environment setup as noted on
> 
> [Mange/rtl8192eu-linux-driver#206 (comment)](https://github.com/Mange/rtl8192eu-linux-driver/issues/206#issuecomment-742884014)
> 
> scripts/ipv6-helper.sh is missing I don't know if is mandatory.

Instentless

**Comment by CGarces** [comment]
Instentless?

I'm just trying reproducing your behaviour.
I assume that there is a error including sta_info.h (is getting something diferent than include/sta_info.h at rtl8192eu). but I can identify the problem without the build environment.
Compile open OpenWRT on my Celeron laptop will take a lot of time, please be patience.

**Comment by xmapst** [comment]
> Instentless?
> 
> I'm just trying reproducing your behaviour.
> I assume that there is a error including sta_info.h (is getting something diferent than include/sta_info.h at rtl8192eu). but I can identify the problem without the build environment.
> Compile open OpenWRT on my Celeron laptop will take a lot of time, please be patience.

Hi, have you found the cause of the problem?

**Comment by CGarces** [comment]
> > Instentless?
> > I'm just trying reproducing your behaviour.
> > I assume that there is a error including sta_info.h (is getting something diferent than include/sta_info.h at rtl8192eu). but I can identify the problem without the build environment.
> > Compile open OpenWRT on my Celeron laptop will take a lot of time, please be patience.
> 
> Hi, have you found the cause of the problem?

No.
The build script not works for me, the process fails before the rtl8192eu build.
I'm trying to reproduce the error with
`$ make -j1 V=s package/rtl8192eu/compile`

But I can't find how fix it.

**Comment by CGarces** [comment]
Ok, I have a workarround to include the correct file.
https://github.com/CGarces/rtl8192eu-linux-driver/commit/2f31fe5ecd7fd766e14ea8d2df8ad8ffa8b0541c
But build still failing for me.

**Comment by CGarces** [comment]
Ok, next step

Try to build the module with the commit at CGarces/rtl8192eu-linux-driver@2f31fe5

And comment this line:
https://github.com/Mange/rtl8192eu-linux-driver/blob/realtek-4.4.x/os_dep/linux/ioctl_cfg80211.c#L9948

Looks like the kernel backports introduced by OpenWRT cause the compilation problem, I need to find how fix it.

**Comment by xmapst** [comment]
> Ok, next step
> 
> Try to build the module with the commit at [CGarces/rtl8192eu-linux-driver@2f31fe5](https://github.com/CGarces/rtl8192eu-linux-driver/commit/2f31fe5)
> 
> And comment this line:
> https://github.com/Mange/rtl8192eu-linux-driver/blob/realtek-4.4.x/os_dep/linux/ioctl_cfg80211.c#L9948
> 
> Looks like the kernel backports introduced by OpenWRT cause the compilation problem, I need to find how fix it.

All right! Looking forward to your solution
